### ISSUE TITLE
Could not find type 'SpyNote_V6._4.SN.ThemeTabControl

### ISSUE THREAD

**Issue by tusarr10** [hamzaharoon1314/SpyNote#2]
Could not find type 'SpyNote_V6._4.SN.ThemeTabControl'. Please make sure that  the assembly that contains this type is referenced. | Could not find type 'SpyNote_V6._4.SN.ThemeTabControl'. Please make sure that  the assembly that contains this type is referenced.
-- | --
Could not find type 'SpyNote_V6._4.SN.ThemeTabControl'. Please make sure that  the assembly that contains this type is referenced.
 why thhis occer ??

**Comment by DrWeabo** [comment]
You are very stupid, you have to build the application first so that no errors occur ...
